import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, double, boolean, json } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Demo product catalog */
export const products = mysqlTable("products", {
  id: int("id").autoincrement().primaryKey(),
  code: varchar("code", { length: 32 }).notNull().unique(),
  name: varchar("name", { length: 128 }).notNull(),
  category: varchar("category", { length: 64 }).notNull(),
  price: double("price").notNull(),
  sellingPoints: text("sellingPoints").notNull(),
  thumbnailUrl: text("thumbnailUrl"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

/** Performance metrics of generated TikTok videos */
export const videos = mysqlTable("videos", {
  id: int("id").autoincrement().primaryKey(),
  productId: int("productId").notNull(),
  variant: varchar("variant", { length: 32 }).notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  hook: text("hook"),
  thumbnailUrl: text("thumbnailUrl"),
  videoUrl: text("videoUrl"),
  views: int("views").default(0).notNull(),
  completionRate: double("completionRate").default(0).notNull(),
  engagementRate: double("engagementRate").default(0).notNull(),
  gpm: double("gpm").default(0).notNull(),
  ctr: double("ctr").default(0).notNull(),
  revenue: double("revenue").default(0).notNull(),
  status: mysqlEnum("status", ["winner", "normal", "underperform"]).default("normal").notNull(),
  publishedAt: timestamp("publishedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

/** Script variants generated by the AI */
export const scripts = mysqlTable("scripts", {
  id: int("id").autoincrement().primaryKey(),
  productId: int("productId").notNull(),
  variant: varchar("variant", { length: 32 }).notNull(),
  strategy: varchar("strategy", { length: 64 }).notNull(),
  content: text("content").notNull(),
  hook: text("hook"),
  pain: text("pain"),
  cta: text("cta"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

/** Auto-triggered ad campaigns */
export const adCampaigns = mysqlTable("adCampaigns", {
  id: int("id").autoincrement().primaryKey(),
  videoId: int("videoId").notNull(),
  campaignName: varchar("campaignName", { length: 128 }).notNull(),
  campaignType: varchar("campaignType", { length: 32 }).default("Spark Ads").notNull(),
  dailyBudget: double("dailyBudget").notNull(),
  bidStrategy: varchar("bidStrategy", { length: 64 }).notNull(),
  audience: text("audience"),
  triggerGpm: double("triggerGpm").notNull(),
  status: varchar("status", { length: 32 }).default("ACTIVE").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Product = typeof products.$inferSelect;
export type Video = typeof videos.$inferSelect;
export type Script = typeof scripts.$inferSelect;
export type AdCampaign = typeof adCampaigns.$inferSelect;
